name: Test Deployment

# When to run tests.
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tag:
    # Name
    name: Test Deployment
    
    # Virtual Environment to use
    # @see: https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04

    # Steps to deploy to wordpress.org
    steps:
      # Checkout (copy) this repository's Plugin to this VM.
      - name: Checkout Plugin
        uses: actions/checkout@v2

      # Installs required packages that must be included in the Plugin
      # as specified in composer.json's "require" section.
      # "require-dev" is ignored by design, as these are only needed for
      # testing
      - name: Run Composer
        run: composer install --no-dev

      # Debug: List contents to confirm what would be sent to wordpress.org
      - name: List
        run: |
          ls
          cd vendor
          ls
          cd convertkit
          ls
          cd wordpress-libs
          ls
          cd src
          ls
